/**
 * UUID工具函数
 * @description 提供UUID生成、验证等功能，支持文件上传策略B
 * @author system
 */

/**
 * @description 生成UUID工具函数
 * @returns {string} 生成的UUID字符串
 */
export function generateUUID() {
  // 使用crypto.randomUUID()（现代浏览器支持）
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  
  // 降级方案：使用Math.random()
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

/**
 * @description 验证UUID格式是否正确
 * @param {string} uuid - 待验证的UUID字符串
 * @returns {boolean} 是否为有效的UUID格式
 */
export function isValidUUID(uuid) {
  if (!uuid || typeof uuid !== 'string') {
    return false;
  }
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(uuid);
}

/**
 * @description 验证是否为数字ID格式
 * @param {string|number} id - 待验证的ID
 * @returns {boolean} 是否为数字ID格式
 */
export function isNumericId(id) {
  if (id === null || id === undefined) {
    return false;
  }
  const str = String(id);
  return /^\d+$/.test(str);
}

/**
 * @description 判断ID类型（UUID或数字）
 * @param {string} id - 待判断的ID
 * @returns {'uuid'|'numeric'|'invalid'} ID类型
 */
export function getIdType(id) {
  if (isValidUUID(id)) {
    return 'uuid';
  }
  if (isNumericId(id)) {
    return 'numeric';
  }
  return 'invalid';
}

/**
 * @description 为业务实体生成UUID
 * @param {string} businessType - 业务类型（HERITAGE_ITEM, ACTIVITY等）
 * @returns {string} 生成的UUID
 */
export function generateBusinessUUID(businessType) {
  const uuid = generateUUID();
  
  // 可以在这里添加业务类型相关的逻辑，比如日志记录
  console.log(`Generated UUID for ${businessType}:`, uuid);
  
  return uuid;
}

/**
 * @description UUID缓存管理（用于文件上传场景）
 */
class UUIDCache {
  constructor() {
    this.cache = new Map();
  }

  /**
   * 为业务类型生成并缓存UUID
   * @param {string} businessType - 业务类型
   * @param {string} key - 缓存键（可选，默认使用businessType）
   * @returns {string} UUID
   */
  getOrGenerate(businessType, key = businessType) {
    if (this.cache.has(key)) {
      return this.cache.get(key);
    }
    
    const uuid = generateBusinessUUID(businessType);
    this.cache.set(key, uuid);
    return uuid;
  }

  /**
   * 获取缓存的UUID
   * @param {string} key - 缓存键
   * @returns {string|null} UUID或null
   */
  get(key) {
    return this.cache.get(key) || null;
  }

  /**
   * 设置UUID到缓存
   * @param {string} key - 缓存键
   * @param {string} uuid - UUID值
   */
  set(key, uuid) {
    if (isValidUUID(uuid)) {
      this.cache.set(key, uuid);
    } else {
      console.warn('Invalid UUID format:', uuid);
    }
  }

  /**
   * 清除缓存
   * @param {string} key - 缓存键（可选，不传则清除所有）
   */
  clear(key) {
    if (key) {
      this.cache.delete(key);
    } else {
      this.cache.clear();
    }
  }

  /**
   * 获取所有缓存的UUID
   * @returns {Object} 所有缓存的UUID对象
   */
  getAll() {
    return Object.fromEntries(this.cache);
  }
}

// 创建全局UUID缓存实例
export const uuidCache = new UUIDCache();

/**
 * @description 业务实体UUID管理器
 * 用于管理不同业务实体的UUID生成和使用
 */
export class BusinessUUIDManager {
  constructor(businessType) {
    this.businessType = businessType;
    this.uuid = null;
    this.isGenerated = false;
  }

  /**
   * 生成UUID
   * @returns {string} 生成的UUID
   */
  generate() {
    if (!this.uuid) {
      this.uuid = generateBusinessUUID(this.businessType);
      this.isGenerated = true;
    }
    return this.uuid;
  }

  /**
   * 获取UUID（如果未生成则自动生成）
   * @returns {string} UUID
   */
  get() {
    return this.uuid || this.generate();
  }

  /**
   * 设置UUID
   * @param {string} uuid - UUID值
   */
  set(uuid) {
    if (isValidUUID(uuid)) {
      this.uuid = uuid;
      this.isGenerated = false; // 标记为外部设置
    } else {
      throw new Error('Invalid UUID format');
    }
  }

  /**
   * 重置UUID
   */
  reset() {
    this.uuid = null;
    this.isGenerated = false;
  }

  /**
   * 是否已生成UUID
   * @returns {boolean}
   */
  hasUUID() {
    return !!this.uuid;
  }

  /**
   * 是否为自动生成的UUID
   * @returns {boolean}
   */
  isAutoGenerated() {
    return this.isGenerated;
  }
}

/**
 * @description 创建业务UUID管理器的工厂函数
 * @param {string} businessType - 业务类型
 * @returns {BusinessUUIDManager} UUID管理器实例
 */
export function createBusinessUUIDManager(businessType) {
  return new BusinessUUIDManager(businessType);
}

// 预定义的业务类型常量
export const BUSINESS_TYPES = {
  HERITAGE_ITEM: 'HERITAGE_ITEM',
  ACTIVITY: 'ACTIVITY', 
  COURSE: 'COURSE',
  SHOP_PRODUCT: 'SHOP_PRODUCT',
  INHERITOR: 'INHERITOR',
  USER_AVATAR: 'USER_AVATAR'
};

/**
 * @description 检查业务类型是否支持UUID策略B
 * @param {string} businessType - 业务类型
 * @returns {boolean} 是否支持UUID策略B
 */
export function supportsUUIDStrategyB(businessType) {
  const supportedTypes = [
    BUSINESS_TYPES.HERITAGE_ITEM,
    BUSINESS_TYPES.ACTIVITY,
    BUSINESS_TYPES.COURSE,
    BUSINESS_TYPES.SHOP_PRODUCT,
    BUSINESS_TYPES.INHERITOR
  ];
  return supportedTypes.includes(businessType);
}







